# Instructions
1. Get a dataset on Kaggle per your assigned ML problem (classification or regression)
2. Identify whether it's binary, multiclass, multilabel
3. Identify the target feature
4. Train the model on your dataset (using Decision Trees & Random Forest)
5. Evaluate the model using the appropriate metrics for your ML problem (Accuracy, F1 Score, AUC/ROC, MAE, MAPE, R^2)

In [62]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import plotly.figure_factory as ff

# Exploratory data Analaysis

In [10]:
df = pd.read_csv("datasets/diabetes.csv")

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   patient_number   390 non-null    int64
 1   cholesterol      390 non-null    int64
 2   glucose          390 non-null    int64
 3   hdl_chol         390 non-null    int64
 4   chol_hdl_ratio   390 non-null    str
 5   age              390 non-null    int64
 6   gender           390 non-null    str
 7   height           390 non-null    int64
 8   weight           390 non-null    int64
 9   bmi              390 non-null    str
 10  systolic_bp      390 non-null    int64
 11  diastolic_bp     390 non-null    int64
 12  waist            390 non-null    int64
 13  hip              390 non-null    int64
 14  waist_hip_ratio  390 non-null    str
 15  diabetes         390 non-null    str
dtypes: int64(11), str(5)
memory usage: 48.9 KB

In [12]:
df.head()

,patient_number,cholesterol,glucose,hdl_chol,chol_hdl_ratio,age,gender,height,weight,bmi,systolic_bp,diastolic_bp,waist,hip,waist_hip_ratio,diabetes
0,1,193,77,49,"3,9",19,female,61,119,"22,5",118,70,32,38,"0,84",No diabetes
1,2,146,79,41,"3,6",19,female,60,135,"26,4",108,58,33,40,"0,83",No diabetes
2,3,217,75,54,4,20,female,67,187,"29,3",110,72,40,45,"0,89",No diabetes
3,4,226,97,70,"3,2",20,female,64,114,"19,6",122,64,31,39,"0,79",No diabetes
4,5,164,91,67,"2,4",20,female,70,141,"20,2",122,86,32,39,"0,82",No diabetes

# Data Cleaning

In [ ]:
# change the , to periods for the columns and also make the col float type instead of string
cols = ['chol_hdl_ratio', 'bmi', 'waist_hip_ratio']
for col in cols:
    df[col] = df[col].str.replace(',', '.')
    df[col] = pd.to_numeric(df[col])

df

,patient_number,cholesterol,glucose,hdl_chol,chol_hdl_ratio,age,gender,height,weight,bmi,systolic_bp,diastolic_bp,waist,hip,waist_hip_ratio,diabetes
0,1,193,77,49,3.9,19,female,61,119,22.5,118,70,32,38,0.84,No diabetes
1,2,146,79,41,3.6,19,female,60,135,26.4,108,58,33,40,0.83,No diabetes
2,3,217,75,54,4.0,20,female,67,187,29.3,110,72,40,45,0.89,No diabetes
3,4,226,97,70,3.2,20,female,64,114,19.6,122,64,31,39,0.79,No diabetes
4,5,164,91,67,2.4,20,female,70,141,20.2,122,86,32,39,0.82,No diabetes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,386,227,105,44,5.2,83,female,59,125,25.2,150,90,35,40,0.88,No diabetes
386,387,226,279,52,4.3,84,female,60,192,37.5,144,88,41,48,0.85,Diabetes
387,388,301,90,118,2.6,89,female,61,115,21.7,218,90,31,41,0.76,No diabetes
388,389,232,184,114,2.0,91,female,61,127,24.0,170,82,35,38,0.92,Diabetes
389,390,165,94,69,2.4,92,female,62,217,39.7,160,82,51,51,1.00,No diabetes

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   patient_number   390 non-null    int64
 1   cholesterol      390 non-null    int64
 2   glucose          390 non-null    int64
 3   hdl_chol         390 non-null    int64
 4   chol_hdl_ratio   390 non-null    float64
 5   age              390 non-null    int64
 6   gender           390 non-null    str
 7   height           390 non-null    int64
 8   weight           390 non-null    int64
 9   bmi              390 non-null    float64
 10  systolic_bp      390 non-null    int64
 11  diastolic_bp     390 non-null    int64
 12  waist            390 non-null    int64
 13  hip              390 non-null    int64
 14  waist_hip_ratio  390 non-null    float64
 15  diabetes         390 non-null    str
dtypes: float64(3), int64(11), str(2)
memory usage: 48.9 KB

In [ ]:
# use one hote encoding to convert the gender, and diabetes column to bools
df = pd.get_dummies(df, columns=[['gender','diabetes']], drop_first=True)

In [33]:
df
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   patient_number        390 non-null    int64
 1   cholesterol           390 non-null    int64
 2   glucose               390 non-null    int64
 3   hdl_chol              390 non-null    int64
 4   chol_hdl_ratio        390 non-null    float64
 5   age                   390 non-null    int64
 6   height                390 non-null    int64
 7   weight                390 non-null    int64
 8   bmi                   390 non-null    float64
 9   systolic_bp           390 non-null    int64
 10  diastolic_bp          390 non-null    int64
 11  waist                 390 non-null    int64
 12  hip                   390 non-null    int64
 13  waist_hip_ratio       390 non-null    float64
 14  gender_male           390 non-null    bool
 15  diabetes_No diabetes  390 non-null    bool
dtypes: bool(2), float64(3), int64(11)
memory usage: 43.5 KB

# Training

In [34]:
X = df.drop(columns=['diabetes_No diabetes'])
y = df['diabetes_No diabetes']

In [35]:
# split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=2)

# Decision Tree

In [66]:
# Create and train 
model=DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [67]:
# Predict
y_pred = model.predict(X_test)
y_pred

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True,  True, False,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [ ]:
# Recall — "Of all actual cases of this class, how many did the model catch?"
# Precision — "Of all the times the model predicted this class, how often was it right?"
#F1-Score — Balanced average of precision and recall. Use this when the classes are imbalanced.
#Support — How many actual samples of each class are in the test set
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.83      0.77      0.80        13
        True       0.95      0.97      0.96        65

    accuracy                           0.94        78
   macro avg       0.89      0.87      0.88        78
weighted avg       0.93      0.94      0.93        78

In [69]:
dc_cm = confusion_matrix(y_test, y_pred)

labels = ['No diabetes', 'Diabetes']

fig = ff.create_annotated_heatmap(
    z=dc_cm,
    x=labels,
    y=labels,
    colorscale='Blues',
    showscale=True
)
fig.update_layout(
    title='Confusion Matrix',
    xaxis_title='Predicted',
    yaxis_title='Actual'
)
fig.show()

# Random Forest

In [55]:
#n_estimators: number of base learners
rfc = RandomForestClassifier(n_estimators=100, max_depth=15, random_state=2) 
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=15, random_state=2)

In [60]:
rfc_y_pred = rfc.predict(X_test)

In [57]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.90      0.69      0.78        13
        True       0.94      0.98      0.96        65

    accuracy                           0.94        78
   macro avg       0.92      0.84      0.87        78
weighted avg       0.93      0.94      0.93        78

In [ ]:

cm = confusion_matrix(y_test, rfc_y_pred)

labels = ['No Diabetes', 'Diabetes']

fig = ff.create_annotated_heatmap(
    z=cm,
    x=labels,
    y=labels,
    colorscale='Blues',
    showscale=True
)

fig.update_layout(
    title='Confusion Matrix',
    xaxis_title='Predicted',
    yaxis_title='Actual'
)

fig.show()