# Instructions
1. Get a dataset on Kaggle per your assigned ML problem (classification or regression)
2. Identify whether it's binary, multiclass, multilabel
3. Identify the target feature
4. Train the model on your dataset (using Decision Trees & Random Forest)
5. Evaluate the model using the appropriate metrics for your ML problem (Accuracy, F1 Score, AUC/ROC, MAE, MAPE, R^2)

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import plotly.figure_factory as ff
import plotly.express as px

# Exploratory data Analaysis

In [110]:
df = pd.read_csv("datasets/diabetes.csv")

In [111]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   patient_number   390 non-null    int64
 1   cholesterol      390 non-null    int64
 2   glucose          390 non-null    int64
 3   hdl_chol         390 non-null    int64
 4   chol_hdl_ratio   390 non-null    str
 5   age              390 non-null    int64
 6   gender           390 non-null    str
 7   height           390 non-null    int64
 8   weight           390 non-null    int64
 9   bmi              390 non-null    str
 10  systolic_bp      390 non-null    int64
 11  diastolic_bp     390 non-null    int64
 12  waist            390 non-null    int64
 13  hip              390 non-null    int64
 14  waist_hip_ratio  390 non-null    str
 15  diabetes         390 non-null    str
dtypes: int64(11), str(5)
memory usage: 48.9 KB

In [112]:
df.describe()

,patient_number,cholesterol,glucose,hdl_chol,age,height,weight,systolic_bp,diastolic_bp,waist,hip
count,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000
mean,195.500000,207.230769,107.338462,50.266667,46.774359,65.951282,177.407692,137.133333,83.289744,37.869231,42.992308
std,112.727548,44.666005,53.798188,17.279069,16.435911,3.918867,40.407824,22.859528,13.498192,5.760947,5.664342
min,1.000000,78.000000,48.000000,12.000000,19.000000,52.000000,99.000000,90.000000,48.000000,26.000000,30.000000
25%,98.250000,179.000000,81.000000,38.000000,34.000000,63.000000,150.250000,122.000000,75.000000,33.000000,39.000000
50%,195.500000,203.000000,90.000000,46.000000,44.500000,66.000000,173.000000,136.000000,82.000000,37.000000,42.000000
75%,292.750000,229.000000,107.750000,59.000000,60.000000,69.000000,200.000000,148.000000,90.000000,41.000000,46.000000
max,390.000000,443.000000,385.000000,120.000000,92.000000,76.000000,325.000000,250.000000,124.000000,56.000000,64.000000

In [113]:
df.diabetes.value_counts()

diabetes
No diabetes    330
Diabetes        60
Name: count, dtype: int64

In [114]:
df.head()

,patient_number,cholesterol,glucose,hdl_chol,chol_hdl_ratio,age,gender,height,weight,bmi,systolic_bp,diastolic_bp,waist,hip,waist_hip_ratio,diabetes
0,1,193,77,49,"3,9",19,female,61,119,"22,5",118,70,32,38,"0,84",No diabetes
1,2,146,79,41,"3,6",19,female,60,135,"26,4",108,58,33,40,"0,83",No diabetes
2,3,217,75,54,4,20,female,67,187,"29,3",110,72,40,45,"0,89",No diabetes
3,4,226,97,70,"3,2",20,female,64,114,"19,6",122,64,31,39,"0,79",No diabetes
4,5,164,91,67,"2,4",20,female,70,141,"20,2",122,86,32,39,"0,82",No diabetes

In [115]:
px.histogram(df, x='gender', color='diabetes', barmode='group', title='Diabetes by Gender')

# Data Cleaning

In [116]:
# Drop unneeded columns
df.drop(columns=['patient_number'], inplace=True)

In [117]:
# change the , to periods for the columns and also make the col float type instead of string
cols = ['chol_hdl_ratio', 'bmi', 'waist_hip_ratio']
for col in cols:
    df[col] = df[col].str.replace(',', '.')
    df[col] = pd.to_numeric(df[col])

df

,cholesterol,glucose,hdl_chol,chol_hdl_ratio,age,gender,height,weight,bmi,systolic_bp,diastolic_bp,waist,hip,waist_hip_ratio,diabetes
0,193,77,49,3.9,19,female,61,119,22.5,118,70,32,38,0.84,No diabetes
1,146,79,41,3.6,19,female,60,135,26.4,108,58,33,40,0.83,No diabetes
2,217,75,54,4.0,20,female,67,187,29.3,110,72,40,45,0.89,No diabetes
3,226,97,70,3.2,20,female,64,114,19.6,122,64,31,39,0.79,No diabetes
4,164,91,67,2.4,20,female,70,141,20.2,122,86,32,39,0.82,No diabetes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,227,105,44,5.2,83,female,59,125,25.2,150,90,35,40,0.88,No diabetes
386,226,279,52,4.3,84,female,60,192,37.5,144,88,41,48,0.85,Diabetes
387,301,90,118,2.6,89,female,61,115,21.7,218,90,31,41,0.76,No diabetes
388,232,184,114,2.0,91,female,61,127,24.0,170,82,35,38,0.92,Diabetes
389,165,94,69,2.4,92,female,62,217,39.7,160,82,51,51,1.00,No diabetes

In [118]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cholesterol      390 non-null    int64
 1   glucose          390 non-null    int64
 2   hdl_chol         390 non-null    int64
 3   chol_hdl_ratio   390 non-null    float64
 4   age              390 non-null    int64
 5   gender           390 non-null    str
 6   height           390 non-null    int64
 7   weight           390 non-null    int64
 8   bmi              390 non-null    float64
 9   systolic_bp      390 non-null    int64
 10  diastolic_bp     390 non-null    int64
 11  waist            390 non-null    int64
 12  hip              390 non-null    int64
 13  waist_hip_ratio  390 non-null    float64
 14  diabetes         390 non-null    str
dtypes: float64(3), int64(10), str(2)
memory usage: 45.8 KB

In [119]:
# use one hote encoding to convert the gender, and diabetes column to bools
df = pd.get_dummies(df, columns=['gender','diabetes'], drop_first=True)

In [103]:
df

,cholesterol,glucose,hdl_chol,chol_hdl_ratio,age,height,weight,bmi,systolic_bp,diastolic_bp,waist,hip,waist_hip_ratio,gender_male,diabetes_No diabetes
0,193,77,49,3.9,19,61,119,22.5,118,70,32,38,0.84,False,True
1,146,79,41,3.6,19,60,135,26.4,108,58,33,40,0.83,False,True
2,217,75,54,4.0,20,67,187,29.3,110,72,40,45,0.89,False,True
3,226,97,70,3.2,20,64,114,19.6,122,64,31,39,0.79,False,True
4,164,91,67,2.4,20,70,141,20.2,122,86,32,39,0.82,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,227,105,44,5.2,83,59,125,25.2,150,90,35,40,0.88,False,True
386,226,279,52,4.3,84,60,192,37.5,144,88,41,48,0.85,False,False
387,301,90,118,2.6,89,61,115,21.7,218,90,31,41,0.76,False,True
388,232,184,114,2.0,91,61,127,24.0,170,82,35,38,0.92,False,False
389,165,94,69,2.4,92,62,217,39.7,160,82,51,51,1.00,False,True

In [ ]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cholesterol           390 non-null    int64
 1   glucose               390 non-null    int64
 2   hdl_chol              390 non-null    int64
 3   chol_hdl_ratio        390 non-null    float64
 4   age                   390 non-null    int64
 5   height                390 non-null    int64
 6   weight                390 non-null    int64
 7   bmi                   390 non-null    float64
 8   systolic_bp           390 non-null    int64
 9   diastolic_bp          390 non-null    int64
 10  waist                 390 non-null    int64
 11  hip                   390 non-null    int64
 12  waist_hip_ratio       390 non-null    float64
 13  gender_male           390 non-null    bool
 14  diabetes_No diabetes  390 non-null    bool
dtypes: bool(2), float64(3), int64(10)
memory usage: 40.5 KB

In [102]:
px.box(df, x='diabetes_No diabetes', y='bmi', color='diabetes_No diabetes',title='BMI by Diabetes Status')

In [105]:
# Glucose by diabetes status
px.box(df, x='diabetes_No diabetes', y='glucose', color='diabetes_No diabetes', title='Glucose by Diabetes Status')

In [107]:
px.scatter(df, x='bmi', y='glucose', color='diabetes_No diabetes', hover_data=['age', 'gender_male'], title='BMI vs Glucose')

In [135]:
# Select only numeric columns
corr = df.select_dtypes(include='number').corr()

fig = px.imshow(
    corr,
    text_auto=True,       # show values in cells
    color_continuous_scale='RdBu_r',  # red=negative, blue=positive
    title='Correlation Matrix'
)

fig.show()

# Training

In [120]:
X = df.drop(columns=['diabetes_No diabetes'])
y = df['diabetes_No diabetes']

In [121]:
# split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=2)

# Decision Tree

In [122]:
# Create and train 
model=DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [123]:
# Predict
y_pred = model.predict(X_test)
y_pred

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True, False,  True, False,  True,  True, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True])

In [155]:
dt_y_pred = model.predict(X_train)
print(classification_report(y_train, dt_y_pred))

              precision    recall  f1-score   support

       False       0.94      0.98      0.96        47
        True       1.00      0.99      0.99       265

    accuracy                           0.99       312
   macro avg       0.97      0.98      0.98       312
weighted avg       0.99      0.99      0.99       312

In [124]:
# Recall — "Of all actual cases of this class, how many did the model catch?"
# Precision — "Of all the times the model predicted this class, how often was it right?"
#F1-Score — Balanced average of precision and recall. Use this when the classes are imbalanced.
#Support — How many actual samples of each class are in the test set
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.71      0.77      0.74        13
        True       0.95      0.94      0.95        65

    accuracy                           0.91        78
   macro avg       0.83      0.85      0.84        78
weighted avg       0.91      0.91      0.91        78

array([0.05886087, 0.39760401, 0.05658697, 0.06612834, 0.08510727,
       0.03438047, 0.04893061, 0.05219018, 0.05035966, 0.03769346,
       0.03249133, 0.03494278, 0.04019837, 0.00452568])

In [125]:
dc_cm = confusion_matrix(y_test, y_pred)

labels = ['No diabetes', 'Diabetes']

fig = ff.create_annotated_heatmap(
    z=dc_cm,
    x=labels,
    y=labels,
    colorscale='Blues',
    showscale=True
)
fig.update_layout(
    title='Confusion Matrix',
    xaxis_title='Predicted',
    yaxis_title='Actual'
)
fig.show()

In [162]:
importance_df = pd.DataFrame({
    'feature': X_train.columns,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

fig = px.bar(
    importance_df,
    x='feature',
    y='importance',
    title='Decision Feature Importances'
)
fig.show()

# Random Forest

In [148]:
#n_estimators: number of base learners
rfc = RandomForestClassifier(n_estimators=100, max_depth=25, random_state=2) 
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=25, random_state=2)

In [149]:
rfc_y_pred = rfc.predict(X_test)

In [ ]:
# Performance on test data
print(classification_report(y_test, rfc_y_pred))

              precision    recall  f1-score   support

       False       0.89      0.62      0.73        13
        True       0.93      0.98      0.96        65

    accuracy                           0.92        78
   macro avg       0.91      0.80      0.84        78
weighted avg       0.92      0.92      0.92        78

In [ ]:
# Performance on training data
rfc_y_train_pred = rfc.predict(X_train)
print(classification_report(y_train, rfc_y_train_pred))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00        47
        True       1.00      1.00      1.00       265

    accuracy                           1.00       312
   macro avg       1.00      1.00      1.00       312
weighted avg       1.00      1.00      1.00       312

In [134]:

cm = confusion_matrix(y_test, rfc_y_pred)

labels = ['No Diabetes', 'Diabetes']

fig = ff.create_annotated_heatmap(
    z=cm,
    x=labels,
    y=labels,
    colorscale='Blues',
    showscale=True
)

fig.update_layout(
    title='Confusion Matrix',
    xaxis_title='Predicted',
    yaxis_title='Actual'
)

fig.show()

In [ ]:
# View which feature affected the models decision the most
importance_df = pd.DataFrame({
    'feature': X_train.columns,
    'importance': rfc.feature_importances_
}).sort_values('importance', ascending=False)

fig = px.bar(
    importance_df,
    x='feature',
    y='importance',
    title='Random Forest Feature Importances'
)
fig.show()